name: Auto Assign Reviewers and PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1
        with:
          reviewers: "team/payt-tec/dev"

  auto-assign-pr-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR Creator
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.pull_request.user.login]
            });
